default: &default
  username: postgres
  password: postgres
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: myvideo_development
  host: localhost

test:
  <<: *default
  database: myvideo_test
  host: localhost

staging:
  <<: *default
  database: myvideo_development

production:
  <<: *default
  database: myvideo_development
